---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    g_zserver: http://localhost/zabbix/api_jsonrpc.php
    g_zuser: Admin
    g_zpassword: zabbix
  roles:
  - ../roles/os_zabbix
  post_tasks:

  - zbxapi:
      server: "{{ g_zserver }}"
      user: "{{ g_zuser }}"
      password: "{{ g_zpassword }}"
      zbx_class: Template
      state: list
      params:
        output: extend
    register: templates

  - zbxapi:
      server: "{{ g_zserver }}"
      user: "{{ g_zuser }}"
      password: "{{ g_zpassword }}"
      zbx_class: Template
      state: absent
      params: "{{templates.results | oo_collect('templateid') }}"
