---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
  - ../vars/template_heartbeat.yml
  - ../vars/template_master.yml
  - ../vars/template_node.yml
  - ../vars/template_host.yml
  - ../vars/template_router.yml
  vars:
    g_zserver: http://localhost/zabbix/api_jsonrpc.php
    g_zuser: Admin
    g_zpassword: zabbix
  roles:
  - ../roles/os_zabbix
  post_tasks:
  - zbxapi:
      server: "{{ g_zserver }}"
      user: "{{ g_zuser }}"
      password: "{{ g_zpassword }}"
      zbx_class: Template
      state: list
      params:
        output: extend
    register: templates

  - debug: var=templates

  - name: Include Template
    include: create_template.yml
    vars:
      ctp_template: "{{ g_template_heartbeat }}"
      ctp_zserver: "{{ g_zserver }}"
      ctp_zuser: "{{ g_zuser }}"
      ctp_zpassword: "{{ g_zpassword }}"

  - name: Include Template
    include: create_template.yml
    vars:
      ctp_template: "{{ g_template_master }}"
      ctp_zserver: "{{ g_zserver }}"
      ctp_zuser: "{{ g_zuser }}"
      ctp_zpassword: "{{ g_zpassword }}"

  - name: Include Template
    include: create_template.yml
    vars:
      ctp_template: "{{ g_template_node }}"
      ctp_zserver: "{{ g_zserver }}"
      ctp_zuser: "{{ g_zuser }}"
      ctp_zpassword: "{{ g_zpassword }}"

  - name: Include Template
    include: create_template.yml
    vars:
      ctp_template: "{{ g_template_host }}"
      ctp_zserver: "{{ g_zserver }}"
      ctp_zuser: "{{ g_zuser }}"
      ctp_zpassword: "{{ g_zpassword }}"

  - name: Include Template
    include: create_template.yml
    vars:
      ctp_template: "{{ g_template_router }}"
      ctp_zserver: "{{ g_zserver }}"
      ctp_zuser: "{{ g_zuser }}"
      ctp_zpassword: "{{ g_zpassword }}"
